import image from '../newImg/blanket-2593141_1920.jpg';
import image2 from '../newImg/wristwatch-407096_1920.jpg';

export const products = [
  {
    desc: 'this is a sparkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'Runner Bolt',
    imgSrc: image,
    // RELATED PRODUCTS
  },
  {
    desc: 'this is a sparkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SOLD OUT',
    name: 'Thomas Edison top',
    imgSrc: image2,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: '50% OFF',
    name: 'Luis Vuiton custom dress',
    imgSrc: image2,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: '50% OFF',
    name: 'Luis Vuiton custom dress',
    imgSrc: image2,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 5,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'Balenciaga custom palm',
    imgSrc: image,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'Gucci Handmade Belt',
    imgSrc: image2,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 2,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'Christian Dior Customised boots',
    imgSrc: image2,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: '50% OFF',
    name: 'Luis Vuiton custom dress',
    imgSrc: image2,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'hello wolrd',
    imgSrc: image,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 5,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'hello wolrd',
    imgSrc: image,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'hello wolrd',
    imgSrc: image2,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'hello wolrd',
    imgSrc: image,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'hello wolrd',
    imgSrc: image2,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'hello wolrd',
    imgSrc: image,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: '50% OFF',
    name: 'Luis Vuiton custom dress',
    imgSrc: image2,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'hello wolrd',
    imgSrc: image2,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'hello wolrd',
    imgSrc: image,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'hello wolrd',
    imgSrc: image2,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'hello wolrd',
    imgSrc: image2,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'Balenciagas tailored hoodie ',
    imgSrc: image,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'hello wolrd',
  
    imgSrc: image,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'hello wolrd',
    imgSrc: image2,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'hello wolrd',
    imgSrc: image,
  },
  {
    desc: 'new product has arrived',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['blue', 'yellow', 'green', 'red'],
    price: 200,
    percentOff: 20,
    status: 'SALE',
    name: 'new product',
    imgSrc: image,
  },
  
];
export const LikedItems = [
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['orange', 'yellow', 'green', 'blue'],
    price: 200,
    percentOff: 20,
    status: '50% OFF',
    name: 'Luis Vuiton custom dress',
    imgSrc: image2,
  },
  {
    desc: 'this is a spasrkling descriptio of trhsi item telling you hoe much of a badass this product is',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4,
    colors: ['orange', 'yellow', 'green', 'blue'],
    price: 200,
    percentOff: 20,
    status: '50% OFF',
    name: 'Luis Vuiton custom dress',
    imgSrc: image2,
  },
];